"""Unique ID generation for client order IDs and run IDs."""

from __future__ import annotations

import time
import uuid


def generate_client_order_id(strategy_name: str = "", prefix: str = "bot") -> str:
    """Generate a unique client order ID.

    Format: {prefix}_{strategy}_{timestamp_ms}_{short_uuid}
    Max length: 36 chars (Binance limit)
    """
    ts = int(time.time() * 1000) % 10_000_000_000  # last 10 digits
    short_id = uuid.uuid4().hex[:6]
    strategy_part = strategy_name[:8] if strategy_name else "gen"
    order_id = f"{prefix}_{strategy_part}_{ts}_{short_id}"
    return order_id[:36]


def extract_strategy_from_client_oid(
    client_oid: str,
    known_strategies: list[str] | None = None,
) -> str | None:
    """Infer strategy name from a client_order_id generated by this module.

    Format: bot_{strategy8chars}_{timestamp10d}_{uuid6}

    Returns the best-matching known strategy name, or the raw prefix if no
    known_strategies list is provided.  Returns None if the ID is not in the
    expected format.
    """
    if not client_oid.startswith("bot_"):
        return None

    parts = client_oid.split("_")
    # Expect at least: ["bot", ..., "<10-digit-ts>", "<6-hex-uuid>"]
    if len(parts) < 4:
        return None
    if not parts[-2].isdigit() or len(parts[-2]) != 10:
        return None

    prefix = "_".join(parts[1:-2])  # e.g. "trend_do" or "momentum"

    if not known_strategies:
        return prefix

    # Best match: strategy whose first-8-chars matches the prefix
    for name in known_strategies:
        if name[:8] == prefix[:8]:
            return name

    return prefix


def generate_run_id() -> str:
    """Generate a unique backtest run ID.

    Format: run_{YYYYMMDD_HHMMSS}_{short_uuid}
    """
    ts = time.strftime("%Y%m%d_%H%M%S")
    short_id = uuid.uuid4().hex[:6]
    return f"run_{ts}_{short_id}"
